data_params:
  key: ['x', 'y']
  sort_value: ['id']
  path: 'data/tsp_data.txt'
  min_city: 30
  max_city: 400
  normalize: True
  use_help_func: True
  node_feat_size: 6
  edge_feat_size: 4

train_params:
  batch_size: 5
  memory_size: 1000
  max_episode: 10000
  test_while_training: True   # Required Test Data
  test_freq: 200              # If test_while_training is True
  n_step: 14    # (Recommended Value) => min_city // 2 - 1
  train_epoch: 1
  discount: 0.9
  save_path: 'models/logs'
  save_freq: 1000
  easy_start: 20

test_params:
  max_episode: 50

model_params:
  model: 'S2V'
  p: 32
  load: True
  t: 4
  init_lr: 0.01
  decay_rate: 0.96
  grad_clip: 5
