data_params:
  key: ['x', 'y']
  sort_value: ['id']
  path: 'data/tsp_data.txt'
  min_city: 50
  max_city: 500
  normalize: True
  use_help_func: True

train_params:
  batch_size: 5
  memory_size: 1000
  max_episode: 10000
  test_while_training: True   # Required Test Data
  test_freq: 100              # If test_while_training is True
  n_step: 24    # (Recommended Value) => min_city // 2 - 1
  train_epoch: 1
  discount: 0.9
  save_path: 'models/logs'
  save_freq: 1000

test_params:
  max_episode: 50

model_params:
  model: 'S2V'
  load: True
  t: 4
  lr: 0.00001
